@extends('layouts.app')

@section('content')
<div class="space-y-5">
    <a class="inline-flex items-center gap-2 text-sm font-semibold text-teal hover:underline" href="{{ $trackingUrl ?? route('dashboard') }}"><span aria-hidden="true">&larr;</span> {{ isset($trackingUrl) ? 'Back to project tracking' : 'Back to dashboard' }}</a>
    <section class="project-hero">
        <div class="flex flex-wrap items-start justify-between gap-4">
            <div class="min-w-0 flex-1"><p class="mb-3 text-xs font-semibold uppercase tracking-widest text-teal-200">Project profile · {{ $record->data['reference'] ?? 'No reference' }}</p><h1 class="font-display text-2xl font-extrabold leading-snug sm:text-3xl">{{ $record->data['name'] }}</h1><p class="mt-3 text-sm text-teal-100/80">{{ $record->data['agency'] ?? 'Implementing agency not assigned' }}</p></div>
            @if($record->exists)<a class="rounded-lg border border-white/25 bg-white/10 px-4 py-2.5 text-sm font-semibold hover:bg-white/20" href="{{ route('projects.edit', $record) }}">Edit project</a>@endif
        </div>
        <div class="mt-5 flex flex-wrap gap-2 text-xs"><span class="rounded-full bg-white/15 px-3 py-1.5">{{ $record->data['stage'] ?? 'Stage not set' }}</span><span class="rounded-full bg-white/15 px-3 py-1.5">{{ $record->data['status'] ?? 'Active' }}</span>@if(isset($sample) || ($dashboardDemo ?? false))<span class="rounded-full bg-amber-200/20 px-3 py-1.5 text-amber-100">Demo data</span>@endif</div>
    </section>
    @if(!empty($record->data['reasons']))<div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><h2 class="font-semibold">Project requires attention</h2><ul class="mt-2 list-inside list-disc">@foreach($record->data['reasons'] as $reason)<li>{{ $reason }}</li>@endforeach</ul></div>@endif
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <article class="tracking-stat tracking-stat-teal"><p class="eyebrow">Project cost</p><p class="mt-3 break-words font-display text-2xl font-extrabold">{{ isset($record->data['cost']) && is_numeric($record->data['cost']) ? number_format((float) $record->data['cost'], 2) : 'Not specified' }}</p><p class="mt-2 text-xs text-teal">{{ $record->data['currency'] ?? 'Currency not specified' }}</p></article>
        <article class="tracking-stat tracking-stat-blue"><p class="eyebrow">Implementing agency</p><p class="mt-3 font-display text-lg font-bold">{{ $record->data['agency'] ?? 'Not assigned' }}</p><p class="mt-2 text-xs text-slate-500">Delivery responsibility</p></article>
        <article class="tracking-stat tracking-stat-green"><p class="eyebrow">Responsible officer</p><p class="mt-3 font-display text-lg font-bold">{{ ($record->data['officer'] ?? '') ?: 'Not assigned' }}</p><p class="mt-2 text-xs text-slate-500">Project coordination</p></article>
        <article class="tracking-stat"><p class="eyebrow">Related documents</p><p class="mt-3 font-display text-2xl font-extrabold">{{ count($record->data['attachments'] ?? []) }}</p><a class="mt-2 inline-block text-xs font-semibold text-teal hover:underline" href="#project-documents">View document library &darr;</a></article>
    </div>
    <div class="grid items-start gap-5 lg:grid-cols-[minmax(0,1.5fr)_minmax(0,1fr)]">
        <div class="min-w-0 space-y-5">
            <section class="panel p-5 sm:p-6"><p class="eyebrow mb-2">About the project</p><h2 class="font-display text-lg font-bold">Overview</h2><p class="mt-4 whitespace-pre-wrap break-words text-sm leading-7 text-slate-600">{{ ($record->data['description'] ?? '') ?: 'No project description has been added yet.' }}</p><dl class="mt-6 grid gap-5 border-t border-line pt-5 sm:grid-cols-2">@foreach(['reference' => 'Reference number', 'status' => 'Project status'] as $field => $label)<div><dt class="text-xs text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm font-semibold">{{ $record->data[$field] ?? 'Not specified' }}</dd></div>@endforeach</dl></section>
            <section class="panel p-5 sm:p-6"><h2 class="font-display text-lg font-bold">Coverage & partners</h2><div class="mt-5 space-y-5">@foreach(['districts' => 'Districts', 'sectors' => 'Sectors', 'partners' => 'Development partners / donors'] as $field => $label)<div><h3 class="mb-2 text-xs font-semibold text-slate-500">{{ $label }}</h3><div class="flex flex-wrap gap-2">@forelse((array) ($record->data[$field] ?? []) as $value)<span class="rounded-lg border border-teal/10 bg-teal/5 px-3 py-1.5 text-xs font-medium text-teal">{{ $value }}</span>@empty<span class="text-sm text-slate-400">Not specified</span>@endforelse</div></div>@endforeach</div></section>
            <section class="panel scroll-mt-28 p-5 sm:p-6" id="project-documents"><div class="flex items-center justify-between gap-4"><h2 class="font-display text-lg font-bold">Related documents</h2><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-500">{{ count($record->data['attachments'] ?? []) }} files</span></div><div class="mt-4 divide-y divide-line">@forelse($record->data['attachments'] ?? [] as $index => $document)<div class="flex items-center justify-between gap-3 py-4"><div class="min-w-0"><p class="break-words text-sm font-semibold">{{ $document['title'] }}</p><p class="mt-1 text-xs text-slate-400">Uploaded {{ $document['uploaded_at'] ?? 'date unavailable' }}</p></div>@if($record->exists)<a class="shrink-0 rounded-lg bg-teal/10 px-3 py-2 text-xs font-semibold text-teal" href="{{ route('projects.documents.download', [$record, $index]) }}">Download</a>@endif</div>@empty<div class="rounded-xl border border-dashed border-slate-200 bg-slate-50/50 px-5 py-8 text-center"><p class="text-sm font-semibold text-slate-500">No documents attached yet</p><p class="mt-2 text-xs text-slate-400">Project approvals, plans, and supporting files will appear here.</p>@if($record->exists)<a class="mt-4 inline-block text-xs font-semibold text-teal hover:underline" href="{{ route('projects.edit', $record) }}">Upload documents</a>@endif</div>@endforelse</div></section>
        </div>
        <div class="min-w-0 space-y-5">
            <section class="panel p-5 sm:p-6"><p class="eyebrow mb-2">Delivery timeline</p><h2 class="font-display text-lg font-bold">Key dates</h2><dl class="project-timeline mt-6">@foreach(['start' => 'Planned start date', 'actual_start' => 'Actual start date', 'completion' => 'Planned completion date', 'actual_completion' => 'Actual completion date'] as $field => $label)<div><dt class="text-xs text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm font-semibold">{{ ($record->data[$field] ?? '') ?: 'Not set' }}</dd></div>@endforeach</dl></section>
            <section class="panel p-5 sm:p-6"><p class="eyebrow mb-2">Current stage</p><h2 class="font-display text-lg font-bold text-teal">{{ $record->data['stage'] ?? 'Not set' }}</h2><p class="mt-3 text-xs text-slate-400">Stage change date: {{ ($record->data['stage_changed_at'] ?? '') ?: 'Not recorded' }}</p><p class="mt-3 whitespace-pre-wrap break-words text-sm leading-relaxed text-slate-600">{{ ($record->data['stage_change_reason'] ?? '') ?: 'No stage change notes recorded.' }}</p>@if(isset($trackingUrl))<a class="mt-5 inline-flex rounded-lg bg-teal px-4 py-2.5 text-xs font-semibold text-white" href="{{ $trackingUrl }}">View activity tracking &rarr;</a>@endif</section>
        </div>
    </div>
</div>
@endsection
