<div class="portfolio-notice">Sample {{ $tab === 'pipeline' ? 'pipeline' : 'physical' }} components · Placeholder progress and dates for layout review. {{ $tab === 'pipeline' ? 'The highlighted component marks the sample current position.' : 'Expand a component to see its sub-components.' }}</div>
<section class="panel component-chart-panel p-5 sm:p-6"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="font-display text-base font-bold">{{ $tab === 'pipeline' ? 'Stage 1 · Pipeline journey' : 'Stage 2 · Physical component progress' }}</h2><span class="portfolio-pill">{{ number_format($components->avg('progress'), 1) }}% sample progress</span></div>
@if($tab === 'pipeline')
<div class="pipeline-status-legend" aria-label="Component status colors"><span data-state="Completed">Completed</span><span data-state="Ongoing">On track</span><span data-state="Delayed">Delayed</span><span data-state="Not started">Not started</span></div>
<nav class="pipeline-chevron-scroll" aria-label="Pipeline components" data-pipeline-navigation>
    <div class="pipeline-chevrons">@foreach($components as $component)<a href="#component-{{ $loop->iteration }}" class="pipeline-chevron {{ $component['current'] ? 'is-current' : '' }}" data-state="{{ $component['status'] }}" aria-controls="component-{{ $loop->iteration }}" aria-expanded="{{ $component['current'] ? 'true' : 'false' }}" @if($component['current']) aria-current="step" @endif><span class="pipeline-chevron-position">{{ $component['current'] ? 'Current component' : 'Step '.$loop->iteration }}</span><strong>{{ $component['name'] }}</strong><span>{{ $component['status'] === 'Ongoing' ? 'On track' : $component['status'] }}</span><b>{{ $component['progress'] }}%</b></a>@endforeach</div>
</nav>
@else<div class="portfolio-bars mt-6">@foreach($components as $component)<a class="portfolio-bar" href="#component-{{ $loop->iteration }}"><span class="portfolio-bar-label">{{ $component['name'] }}</span><span class="portfolio-bar-track"><span class="{{ $component['status'] === 'Delayed' ? 'is-delayed' : '' }}" style="width: {{ $component['progress'] }}%"></span></span><strong>{{ $component['progress'] }}%</strong></a>@endforeach</div>@endif
</section>
<section class="panel component-table-panel overflow-hidden" @if($tab === 'pipeline') data-pipeline-details @endif><div class="p-5"><h2 class="font-display text-base font-bold">{{ $tab === 'pipeline' ? 'Pipeline component details' : 'Components & sub-components' }}</h2></div>
@foreach($components as $component)<details class="component-details" data-status="{{ $component['status'] }}" id="component-{{ $loop->iteration }}" @if($tab === 'pipeline' ? $component['current'] : $loop->first) open @endif><summary><span><strong>{{ $component['name'] }}</strong><small>{{ $tab === 'pipeline' ? ($component['current'] ? 'Current component' : $component['status']) : count($component['subcomponents']).' sub-components' }}</small></span><span class="portfolio-status" data-status="{{ $component['status'] }}">{{ $component['status'] }}</span><b>{{ $component['progress'] }}%</b></summary><div class="px-5 pb-5"><dl class="project-info-grid mb-5"><div><dt>Start date</dt><dd>{{ $component['start'] }}</dd></div><div><dt>Deadline</dt><dd>{{ $component['due'] }}</dd></div><div><dt>Responsible office</dt><dd>{{ $component['officer'] }}</dd></div><div><dt>Remarks</dt><dd>{{ $component['status'] === 'Delayed' ? 'Sample schedule delay requiring follow-up.' : 'Sample component for planning and review.' }}</dd></div></dl>
@if($component['subcomponents'])<div class="overflow-x-auto"><table class="portfolio-table"><thead><tr><th>Sub-component</th><th>Responsible office</th><th>Progress</th><th>Status</th></tr></thead><tbody>@foreach($component['subcomponents'] as $sub)<tr><td>{{ $sub['name'] }}</td><td>{{ $sub['officer'] }}</td><td>{{ $sub['progress'] }}%</td><td>{{ $sub['status'] }}</td></tr>@endforeach</tbody></table></div>@endif</div></details>@endforeach
</section>
@if($record->exists && $work->isNotEmpty())<section class="panel overflow-hidden"><div class="flex flex-wrap items-center justify-between gap-3 p-5"><div><h2 class="font-display text-base font-bold">Recorded project activities</h2><p class="mt-1 text-xs text-slate-500">Live deadlines are used for project issue detection.</p></div><a class="text-sm font-semibold text-teal" href="{{ route('projects.show', $record) }}">Manage activities & comments →</a></div><div class="overflow-x-auto"><table class="portfolio-table"><thead><tr><th>Activity</th><th>Stage</th><th>Deadline</th><th>Status</th></tr></thead><tbody>@foreach($work as $item)<tr><td>{{ $item->data['name'] }}</td><td>{{ $item->data['stage'] ?? 'Not set' }}</td><td>{{ $item->data['due'] ?? 'Not set' }}</td><td>{{ $item->data['status'] ?? 'Not started' }}</td></tr>@endforeach</tbody></table></div></section>@endif
