<div class="portfolio-notice">Illustrative financial data · Amounts shown in {{ $record->data['currency'] ?? 'PKR' }} millions. Financial issue indicators will be added once defined.</div>
<div class="financial-summary grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
@foreach(['cost' => 'Total project cost', 'foreign' => 'Total foreign value', 'local' => 'Total local value', 'commitment' => 'Net commitment', 'disbursed' => 'Total disbursed', 'undisbursed' => 'Total undisbursed'] as $key => $label)<article class="panel financial-summary-card p-5"><p class="text-xs text-slate-500">{{ $label }}</p><p class="mt-3 font-display text-2xl font-extrabold">{{ number_format($finance[$key] / 1000000, 2) }}</p></article>@endforeach
<article class="panel financial-summary-card p-5"><p class="text-xs text-slate-500">Cumulative disbursement</p><p class="mt-3 font-display text-2xl font-extrabold">{{ $finance['commitment'] > 0 ? number_format($finance['disbursed'] / $finance['commitment'] * 100, 1) : '0.0' }}%</p></article>
<article class="panel financial-summary-card p-5"><p class="text-xs text-slate-500">Sample reporting period</p><p class="mt-3 font-display text-lg font-bold">FY 2024–25 to 2026–27</p></article>
</div>
<form class="panel flex flex-wrap items-end gap-4 p-5" action="{{ $row['url'] }}" method="get"><input type="hidden" name="tab" value="financial"><label class="text-xs font-semibold text-slate-500">Financial year<select class="field mt-2" name="year">@foreach(array_keys($finance['years']) as $option)<option value="{{ $option }}" @selected($year === $option)>FY {{ $option }}</option>@endforeach</select></label><label class="text-xs font-semibold text-slate-500">Quarter<select class="field mt-2" name="quarter"><option value="all">All quarters</option>@foreach(range(1,4) as $option)<option value="{{ $option }}" @selected((string) $quarter === (string) $option)>Q{{ $option }}</option>@endforeach</select></label><button class="portfolio-primary">Update charts</button><p class="pb-2 text-xs text-slate-400">Q1 Jul–Sep · Q2 Oct–Dec · Q3 Jan–Mar · Q4 Apr–Jun</p></form>
<div class="financial-charts grid gap-5 lg:grid-cols-2">
<section class="panel p-6"><h2 class="font-display text-base font-bold">FY {{ $year }} · Disbursement performance</h2><div class="portfolio-bars mt-6">@foreach(['target' => 'Target', 'achieved' => 'Achieved', 'foreign' => 'Foreign allocation', 'local' => 'Local allocation'] as $key => $label)<div class="portfolio-bar financial-bar"><span class="portfolio-bar-label">{{ $label }}</span><span class="portfolio-bar-track"><span style="width: {{ $annual[$key] / max(1, $annual['target'], $annual['achieved'], $annual['foreign']) * 100 }}%"></span></span><strong>{{ number_format($annual[$key] / 1000000, 2) }}</strong></div>@endforeach</div><p class="mt-6 text-sm text-teal">Annual target achieved: <strong>{{ $annual['target'] > 0 ? number_format($annual['achieved'] / $annual['target'] * 100, 1) : '0.0' }}%</strong></p></section>
<section class="panel p-6"><h2 class="font-display text-base font-bold">FY {{ $year }} · {{ $quarter === 'all' ? 'Quarterly' : 'Q'.$quarter }} release & expenditure</h2><div class="mt-3 flex gap-4 text-xs"><span class="text-teal">● Release</span><span class="text-blue-600">● Expenditure</span></div><div class="quarter-chart">@php($maximum = max(1, ...array_column($quarters, 'release')))@foreach($quarters as $number => $values)<div class="quarter-column"><div class="quarter-bars"><div style="height: {{ $values['release'] / $maximum * 100 }}%"><span>{{ number_format($values['release'] / 1000000, 2) }}</span></div><div class="expenditure" style="height: {{ $values['expenditure'] / $maximum * 100 }}%"><span>{{ number_format($values['expenditure'] / 1000000, 2) }}</span></div></div><strong>Q{{ $number }}</strong></div>@endforeach</div></section>
</div>
<section class="panel financial-detail-table overflow-hidden"><h2 class="p-5 font-display text-base font-bold">FY {{ $year }} · Release and expenditure detail</h2><div class="overflow-x-auto"><table class="portfolio-table"><thead><tr><th>Quarter</th><th>Release (millions)</th><th>Expenditure (millions)</th><th>Utilization</th><th>Remarks</th></tr></thead><tbody>@foreach($quarters as $number => $values)<tr><td>Q{{ $number }}</td><td>{{ number_format($values['release'] / 1000000, 2) }}</td><td>{{ number_format($values['expenditure'] / 1000000, 2) }}</td><td>{{ $values['release'] > 0 ? number_format($values['expenditure'] / $values['release'] * 100, 1) : '0.0' }}%</td><td>Illustrative reporting data</td></tr>@endforeach</tbody></table></div></section>
