<?php

return [
    'projects' => [
        'activity_templates' => [
            'concept-note' => ['name' => 'Activity 1', 'legacy_name' => 'Prepare concept note', 'stage' => 'Concept', 'subactivities' => ['identify-needs' => 'Identify project needs', 'define-objectives' => 'Define objectives and scope']],
            'concept-review' => ['name' => 'Activity 2', 'legacy_name' => 'Review project concept', 'stage' => 'Concept', 'subactivities' => ['consult-stakeholders' => 'Consult stakeholders', 'approve-concept' => 'Obtain concept endorsement']],
            'stage-1-activity-3' => ['name' => 'Activity 3', 'stage' => 'Concept', 'subactivities' => []],
            'stage-1-activity-4' => ['name' => 'Activity 4', 'stage' => 'Concept', 'subactivities' => []],
            'stage-1-activity-5' => ['name' => 'Activity 5', 'stage' => 'Concept', 'subactivities' => []],
            'prepare-pc1' => ['name' => 'Activity 1', 'legacy_name' => 'Prepare PC-I', 'stage' => 'PC-I Development', 'subactivities' => ['feasibility' => 'Complete feasibility assessment', 'cost-estimates' => 'Prepare cost estimates']],
            'approve-pc1' => ['name' => 'Activity 2', 'legacy_name' => 'Review and approve PC-I', 'stage' => 'PC-I Development', 'subactivities' => ['technical-review' => 'Complete technical review', 'approval' => 'Obtain approval']],
            'stage-2-activity-3' => ['name' => 'Activity 3', 'stage' => 'PC-I Development', 'subactivities' => []],
            'stage-2-activity-4' => ['name' => 'Activity 4', 'stage' => 'PC-I Development', 'subactivities' => []],
            'stage-2-activity-5' => ['name' => 'Activity 5', 'stage' => 'PC-I Development', 'subactivities' => []],
            'stage-2-activity-6' => ['name' => 'Activity 6', 'stage' => 'PC-I Development', 'subactivities' => []],
            'stage-2-activity-7' => ['name' => 'Activity 7', 'stage' => 'PC-I Development', 'subactivities' => []],
            'stage-2-activity-8' => ['name' => 'Activity 8', 'stage' => 'PC-I Development', 'subactivities' => []],
            'stage-2-activity-9' => ['name' => 'Activity 9', 'stage' => 'PC-I Development', 'subactivities' => []],
            'procurement' => ['name' => 'Activity 1', 'legacy_name' => 'Procurement and mobilization', 'stage' => 'Implementation', 'subactivities' => ['procurement-plan' => 'Prepare procurement plan', 'mobilization' => 'Mobilize implementation team']],
            'delivery' => ['name' => 'Activity 2', 'legacy_name' => 'Delivery and monitoring', 'stage' => 'Implementation', 'subactivities' => ['progress-review' => 'Review implementation progress', 'completion-review' => 'Complete final review and handover']],
            'stage-3-activity-3' => ['name' => 'Activity 3', 'stage' => 'Implementation', 'subactivities' => []],
            'stage-3-activity-4' => ['name' => 'Activity 4', 'stage' => 'Implementation', 'subactivities' => []],
            'stage-3-activity-5' => ['name' => 'Activity 5', 'stage' => 'Implementation', 'subactivities' => []],
            'stage-3-activity-6' => ['name' => 'Activity 6', 'stage' => 'Implementation', 'subactivities' => []],
            'stage-3-activity-7' => ['name' => 'Activity 7', 'stage' => 'Implementation', 'subactivities' => []],
        ],
        'singular' => 'Project',
        'title' => 'Manage projects',
        'description' => 'Project records, current stages, costs and warnings.',
        'columns' => [
            0 => 'name',
            1 => 'cost',
            2 => 'currency',
            3 => 'agency',
            4 => 'districts',
            5 => 'sectors',
            6 => 'partners',
            7 => 'stage',
            8 => 'status',
        ],
        'labels' => [
            0 => 'Project',
            1 => 'Cost',
            2 => 'Currency',
            3 => 'Implementing agency',
            4 => 'Districts',
            5 => 'Sectors',
            6 => 'Development partners',
            7 => 'Stage',
            8 => 'Status',
        ],
        'fields' => [
            0 => [
                0 => 'name',
                1 => 'Project name',
                2 => 'text',
                3 => true,
                4 => [
                ],
            ],
            1 => [
                0 => 'reference',
                1 => 'Reference number',
                2 => 'text',
                3 => true,
                4 => [
                ],
            ],
            2 => [
                0 => 'stage',
                1 => 'Current stage',
                2 => 'select',
                3 => true,
                4 => [
                    0 => 'Concept',
                    1 => 'PC-I Development',
                    2 => 'Implementation',
                ],
            ],
            3 => [
                0 => 'status',
                1 => 'Project status',
                2 => 'select',
                3 => true,
                4 => [
                    0 => 'Active',
                    2 => 'Completed',
                    3 => 'Canceled',
                ],
            ],
            4 => [
                0 => 'description',
                1 => 'Brief description',
                2 => 'textarea',
                3 => false,
                4 => [
                ],
            ],
            5 => [
                0 => 'cost',
                1 => 'Project cost',
                2 => 'number',
                3 => false,
                4 => [
                ],
            ],
            6 => [
                0 => 'currency',
                1 => 'Currency',
                2 => 'text',
                3 => false,
                4 => [
                ],
            ],
            7 => [
                0 => 'agency',
                1 => 'Implementing agency',
                2 => 'select',
                3 => true,
                4 => [
                    0 => 'Health Department',
                    1 => 'Education Department',
                    2 => 'Irrigation Department',
                    3 => 'C&W Department',
                ],
            ],
            8 => [
                0 => 'districts',
                1 => 'Districts',
                2 => 'multiselect',
                3 => false,
                4 => [
                    'Abbottabad',
                    'Bajaur',
                    'Bannu',
                    'Battagram',
                    'Buner',
                    'Charsadda',
                    'Dera Ismail Khan',
                    'Hangu',
                    'Haripur',
                    'Karak',
                    'Khyber',
                    'Kohat',
                    'Kolai-Palas',
                    'Kurram',
                    'Lakki Marwat',
                    'Lower Chitral',
                    'Lower Dir',
                    'Lower Kohistan',
                    'Lower South Waziristan',
                    'Malakand',
                    'Mansehra',
                    'Mardan',
                    'Mohmand',
                    'North Waziristan',
                    'Nowshera',
                    'Orakzai',
                    'Paharpur',
                    'Peshawar',
                    'Shangla',
                    'Swabi',
                    'Swat',
                    'Tank',
                    'Torghar',
                    'Upper Chitral',
                    'Upper Dir',
                    'Upper Kohistan',
                    'Upper South Waziristan',
                    'Upper Swat',
                    'Merged districts',
                ],
            ],
            9 => [
                0 => 'sectors',
                1 => 'Sectors',
                2 => 'multiselect',
                3 => false,
                4 => [
                    0 => 'Health',
                    1 => 'Education',
                    2 => 'Water',
                    3 => 'Transport',
                ],
            ],
            10 => [
                0 => 'partners',
                1 => 'Development partners / donors',
                2 => 'multiselect',
                3 => false,
                4 => [
                    0 => 'ADB',
                    1 => 'World Bank',
                    2 => 'Other',
                ],
            ],
            11 => [
                0 => 'officer',
                1 => 'Responsible officer',
                2 => 'text',
                3 => false,
                4 => [
                ],
            ],
            12 => [
                0 => 'start',
                1 => 'Planned start date',
                2 => 'date',
                3 => false,
                4 => [
                ],
            ],
            13 => [
                0 => 'completion',
                1 => 'Planned completion date',
                2 => 'date',
                3 => false,
                4 => [
                ],
            ],
            14 => [
                0 => 'actual_start',
                1 => 'Actual start date',
                2 => 'date',
                3 => false,
                4 => [
                ],
            ],
            15 => [
                0 => 'actual_completion',
                1 => 'Actual completion date',
                2 => 'date',
                3 => false,
                4 => [
                ],
            ],
            16 => [
                0 => 'stage_changed_at',
                1 => 'Stage change date',
                2 => 'date',
                3 => false,
                4 => [
                ],
            ],
            17 => [
                0 => 'stage_change_reason',
                1 => 'Reason for stage change',
                2 => 'textarea',
                3 => false,
                4 => [
                ],
            ],
        ],
    ],
    'activities' => [
        'singular' => 'Activity',
        'title' => 'Manage activities',
        'description' => 'Predefined and custom activities by project and stage.',
        'columns' => ['name', 'type', 'project', 'stage', 'due', 'status'],
        'labels' => ['Activity', 'Type', 'Project', 'Stage', 'Due date', 'Status'],
        'fields' => [
            ['type', 'Activity type', 'select', true, ['Custom', 'Predefined']],
            ['project_id', 'Project', 'select', true, []],
            ['stage', 'Stage', 'select', true, ['Concept', 'PC-I Development', 'Implementation']],
            ['template_id', 'Predefined activity', 'select', false, []],
            ['name', 'Activity name', 'text', true],
            ['description', 'Brief description', 'textarea', false],
            ['officer', 'Responsible officer or agency', 'text', false],
            ['start', 'Planned start date', 'date', false],
            ['due', 'Due date', 'date', false],
            ['actual_start', 'Actual start date', 'date', false],
            ['actual_completion', 'Actual completion date', 'date', false],
            ['status', 'Status', 'select', true, ['Not Started', 'In Progress', 'Completed', 'On Hold', 'Not Applicable']],
            ['remarks', 'Progress remarks', 'textarea', false],
        ],
    ],
    'subactivities' => [
        'singular' => 'Sub-activity',
        'title' => 'Manage sub-activities',
        'description' => 'Predefined and custom activities by project and stage.',
        'columns' => ['name', 'parent_activity', 'type', 'project', 'stage', 'status'],
        'labels' => ['Sub-activity', 'Parent activity', 'Type', 'Project', 'Stage', 'Status'],
        'fields' => [
            ['type', 'Sub-activity type', 'select', true, ['Custom', 'Predefined']],
            ['project_id', 'Project', 'select', true, []],
            ['stage', 'Stage', 'select', true, ['Concept', 'PC-I Development', 'Implementation']],
            ['parent_id', 'Parent activity', 'select', true, []],
            ['template_id', 'Predefined sub-activity', 'select', false, []],
            ['name', 'Sub-activity name', 'text', true],
            ['description', 'Brief description', 'textarea', false],
            ['officer', 'Responsible officer or agency', 'text', false],
            ['start', 'Planned start date', 'date', false],
            ['due', 'Due date', 'date', false],
            ['actual_start', 'Actual start date', 'date', false],
            ['actual_completion', 'Actual completion date', 'date', false],
            ['status', 'Status', 'select', true, ['Not Started', 'In Progress', 'Completed', 'On Hold', 'Not Applicable']],
            ['remarks', 'Progress remarks', 'textarea', false],
        ],
    ],
    'issues' => [
        'singular' => 'Issue',
        'title' => 'Manage issues',
        'description' => 'Open issues, required actions and resolution follow-up.',
        'columns' => [
            0 => 'name',
            1 => 'project',
            2 => 'priority',
            3 => 'status',
        ],
        'labels' => [
            0 => 'Issue',
            1 => 'Project',
            2 => 'Priority',
            3 => 'Status',
        ],
        'fields' => [
            0 => [
                0 => 'name',
                1 => 'Issue title',
                2 => 'text',
                3 => true,
                4 => [
                ],
            ],
            1 => [
                0 => 'description',
                1 => 'Issue description',
                2 => 'textarea',
                3 => false,
                4 => [
                ],
            ],
            2 => [
                0 => 'project',
                1 => 'Project',
                2 => 'select',
                3 => true,
                4 => [
                    0 => 'Rural Health Centres (Phase I)',
                    1 => 'Secondary Schools Upgradation',
                    2 => 'Urban Flood Protection Scheme',
                ],
            ],
            3 => [
                0 => 'stage',
                1 => 'Affected stage',
                2 => 'select',
                3 => true,
                4 => [
                    0 => 'Concept',
                    1 => 'PC-I Development',
                    2 => 'Implementation',
                ],
            ],
            4 => [
                0 => 'activity',
                1 => 'Affected activity',
                2 => 'text',
                3 => false,
                4 => [
                ],
            ],
            5 => [
                0 => 'subactivity',
                1 => 'Affected sub-activity',
                2 => 'text',
                3 => false,
                4 => [
                ],
            ],
            6 => [
                0 => 'reported_at',
                1 => 'Date reported',
                2 => 'date',
                3 => true,
                4 => [
                ],
            ],
            7 => [
                0 => 'reported_by',
                1 => 'Reported by',
                2 => 'text',
                3 => true,
                4 => [
                ],
            ],
            8 => [
                0 => 'priority',
                1 => 'Priority',
                2 => 'select',
                3 => true,
                4 => [
                    0 => 'Low',
                    1 => 'Medium',
                    2 => 'High',
                ],
            ],
            9 => [
                0 => 'officer',
                1 => 'Responsible officer or agency',
                2 => 'text',
                3 => true,
                4 => [
                ],
            ],
            10 => [
                0 => 'action',
                1 => 'Required action',
                2 => 'textarea',
                3 => false,
                4 => [
                ],
            ],
            11 => [
                0 => 'due',
                1 => 'Target resolution date',
                2 => 'date',
                3 => false,
                4 => [
                ],
            ],
            12 => [
                0 => 'status',
                1 => 'Status',
                2 => 'select',
                3 => true,
                4 => [
                    0 => 'Open',
                    1 => 'Being Addressed',
                    2 => 'Resolved',
                ],
            ],
            13 => [
                0 => 'follow_up',
                1 => 'Follow-up remarks',
                2 => 'textarea',
                3 => false,
                4 => [
                ],
            ],
            14 => [
                0 => 'resolution',
                1 => 'Resolution details',
                2 => 'textarea',
                3 => false,
                4 => [
                ],
            ],
        ],
    ],
    'meetings' => [
        'singular' => 'Meeting',
        'title' => 'Manage meetings',
        'description' => 'Meeting schedules, decisions and pending follow-up actions.',
        'columns' => [
            0 => 'name',
            1 => 'projects',
            2 => 'date',
            3 => 'status',
        ],
        'labels' => [
            0 => 'Meeting',
            1 => 'Related projects',
            2 => 'Date',
            3 => 'Status',
        ],
        'fields' => [
            0 => [
                0 => 'name',
                1 => 'Meeting title',
                2 => 'text',
                3 => true,
                4 => [
                ],
            ],
            1 => [
                0 => 'projects',
                1 => 'Related projects',
                2 => 'multiselect',
                3 => true,
                4 => [
                    0 => 'Rural Health Centres (Phase I)',
                    1 => 'Secondary Schools Upgradation',
                    2 => 'Urban Flood Protection Scheme',
                ],
            ],
            2 => [
                0 => 'date',
                1 => 'Date and time',
                2 => 'datetime-local',
                3 => true,
                4 => [
                ],
            ],
            3 => [
                0 => 'venue',
                1 => 'Venue',
                2 => 'text',
                3 => false,
                4 => [
                ],
            ],
            4 => [
                0 => 'meeting_link',
                1 => 'Online meeting link',
                2 => 'url',
                3 => false,
                4 => [
                ],
            ],
            5 => [
                0 => 'participants',
                1 => 'Participants and organizations',
                2 => 'textarea',
                3 => false,
                4 => [
                ],
            ],
            6 => [
                0 => 'agenda',
                1 => 'Agenda',
                2 => 'textarea',
                3 => false,
                4 => [
                ],
            ],
            7 => [
                0 => 'status',
                1 => 'Status',
                2 => 'select',
                3 => true,
                4 => [
                    0 => 'Scheduled',
                    1 => 'Held',
                    2 => 'Postponed',
                    3 => 'Canceled',
                ],
            ],
            8 => [
                0 => 'minutes',
                1 => 'Meeting minutes',
                2 => 'textarea',
                3 => false,
                4 => [
                ],
            ],
            9 => [
                0 => 'decisions',
                1 => 'Decisions',
                2 => 'textarea',
                3 => false,
                4 => [
                ],
            ],
        ],
    ],
    'reports' => [
        'singular' => 'Report',
        'title' => 'Manage reports',
        'description' => 'Prepare simple project, issue, activity and meeting reports.',
        'columns' => [
            0 => 'name',
            1 => 'type',
            2 => 'period_start',
            3 => 'period_end',
            4 => 'status',
        ],
        'labels' => [
            0 => 'Report',
            1 => 'Report type',
            2 => 'From',
            3 => 'To',
            4 => 'Format',
        ],
        'fields' => [
            0 => [
                0 => 'name',
                1 => 'Report name',
                2 => 'text',
                3 => true,
                4 => [
                ],
            ],
            1 => [
                0 => 'type',
                1 => 'Report type',
                2 => 'select',
                3 => true,
                4 => [
                    0 => 'Projects by stage',
                    1 => 'Projects by sector',
                    2 => 'Projects by development partner',
                    3 => 'Projects by district',
                    4 => 'Projects by agency',
                    5 => 'Individual project progress',
                    6 => 'Unresolved issues',
                    7 => 'Overdue activities',
                    8 => 'Meetings and pending actions',
                ],
            ],
            2 => [
                0 => 'projects',
                1 => 'Projects',
                2 => 'multiselect',
                3 => false,
                4 => [
                    0 => 'Rural Health Centres (Phase I)',
                    1 => 'Secondary Schools Upgradation',
                    2 => 'Urban Flood Protection Scheme',
                ],
            ],
            3 => [
                0 => 'period_start',
                1 => 'Reporting period start',
                2 => 'date',
                3 => false,
                4 => [
                ],
            ],
            4 => [
                0 => 'period_end',
                1 => 'Reporting period end',
                2 => 'date',
                3 => false,
                4 => [
                ],
            ],
            5 => [
                0 => 'status',
                1 => 'Format',
                2 => 'select',
                3 => true,
                4 => [
                    0 => 'PDF',
                    1 => 'Excel',
                ],
            ],
        ],
    ],
    'users' => [
        'singular' => 'User',
        'title' => 'Manage users',
        'description' => 'User accounts, assigned roles and project access.',
        'columns' => [
            0 => 'name',
            1 => 'role',
            2 => 'email',
            3 => 'status',
        ],
        'labels' => [
            0 => 'Name',
            1 => 'Role',
            2 => 'Email',
            3 => 'Status',
        ],
        'fields' => [
            0 => [
                0 => 'name',
                1 => 'Name',
                2 => 'text',
                3 => true,
            ],
            1 => [
                0 => 'email',
                1 => 'Email',
                2 => 'email',
                3 => true,
            ],
            2 => [
                0 => 'role',
                1 => 'Role',
                2 => 'select',
                3 => true,
                4 => [
                    0 => 'Administrator',
                    1 => 'Section Officer',
                    2 => 'Supervisor',
                    3 => 'Implementing Agency Representative',
                    4 => 'Donor Viewer',
                ],
            ],
            3 => [
                0 => 'status',
                1 => 'Account status',
                2 => 'select',
                3 => true,
                4 => [
                    0 => 'Active',
                    1 => 'Inactive',
                ],
            ],
            4 => [
                0 => 'projects',
                1 => 'Assigned projects',
                2 => 'multiselect',
                3 => false,
                4 => [
                    0 => 'Rural Health Centres (Phase I)',
                    1 => 'Secondary Schools Upgradation',
                    2 => 'Urban Flood Protection Scheme',
                ],
            ],
        ],
    ],
    'sectors' => [
        'singular' => 'Sector',
        'title' => 'Manage sectors',
        'description' => 'Maintain project sectors.',
        'columns' => ['name'],
        'labels' => ['Sector name'],
        'fields' => [
            ['name', 'Sector name', 'text', true],
        ],
    ],
    'partners' => [
        'singular' => 'Development partner/Donor',
        'title' => 'Manage development partners/donors',
        'description' => 'Maintain development partners and donors.',
        'columns' => ['name'],
        'labels' => ['Development partner/Donor name'],
        'fields' => [
            ['name', 'Development partner/Donor name', 'text', true],
        ],
    ],
    'references' => [
        'singular' => 'Reference item',
        'title' => 'Manage reference lists',
        'description' => 'Maintain districts, sectors, agencies and development partners.',
        'columns' => [
            0 => 'name',
            1 => 'type',
            2 => 'status',
        ],
        'labels' => [
            0 => 'Name',
            1 => 'List type',
            2 => 'Status',
        ],
        'fields' => [
            0 => [
                0 => 'name',
                1 => 'Reference name',
                2 => 'text',
                3 => true,
            ],
            1 => [
                0 => 'type',
                1 => 'List type',
                2 => 'select',
                3 => true,
                4 => [
                    0 => 'District',
                    1 => 'Sector',
                    2 => 'Implementing agency',
                    3 => 'Development partner',
                ],
            ],
            2 => [
                0 => 'status',
                1 => 'Status',
                2 => 'select',
                3 => true,
                4 => [
                    0 => 'Active',
                    1 => 'Inactive',
                ],
            ],
        ],
    ],
    'roles' => [
        'singular' => 'Role',
        'title' => 'Manage roles',
        'description' => 'Role names and allowed actions.',
        'columns' => [
            0 => 'name',
            1 => 'description',
        ],
        'labels' => [
            0 => 'Role',
            1 => 'Description',
        ],
        'fields' => [
            0 => [
                0 => 'name',
                1 => 'Role name',
                2 => 'text',
                3 => true,
            ],
            1 => [
                0 => 'description',
                1 => 'Description',
                2 => 'textarea',
                3 => false,
            ],
            2 => [
                0 => 'permissions',
                1 => 'Allowed actions',
                2 => 'multiselect',
                3 => false,
                4 => [
                    0 => 'View projects',
                    1 => 'Edit projects',
                    2 => 'Update activities',
                    3 => 'Manage issues',
                    4 => 'Resolve issues',
                    5 => 'Record meetings',
                    6 => 'Upload documents',
                    7 => 'Download reports',
                    8 => 'Archive records',
                    9 => 'Manage users',
                    10 => 'Manage reference lists',
                ],
            ],
        ],
    ],
];
